# Generated by Django 5.1.2 on 2024-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_reply_delay',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_reply_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
