# Generated by Django 5.1.2 on 2024-11-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
